# fly.toml app configuration file generated for Singularity Player backend

app = "singularity-player-backend"
primary_region = "bos"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb" # Highly recommended to prevent OOM errors when running concurrent yt-dlp/ffmpeg streams

[mounts]
  source = "singularity_storage"
  destination = "/app/uploads"
